/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type D20GLTF = GLTF & {
  nodes: {
    D20_1: THREE.Mesh;
    D20_2: THREE.Mesh;
  };
  materials: {
    D20Base: THREE.MeshStandardMaterial;
    D20Numbers: THREE.MeshStandardMaterial;
  };
};

type D20ModelProps = {
  color?: THREE.ColorRepresentation;
} & React.ComponentProps<"group">;

export function D20Model({ color = "#a855f7", ...rest }: D20ModelProps) {
  const { nodes, materials } = useGLTF(
    "/models/d20-transformed.glb",
  ) as unknown as D20GLTF;

  return (
    <group {...rest} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.D20_1.geometry}>
          <meshStandardMaterial color={color} roughness={0.175} />
        </mesh>
        <mesh geometry={nodes.D20_2.geometry} material={materials.D20Numbers} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/d20-transformed.glb");
